Adicionando as variáveis contextData e extraData na documentação
zenvia/zenvia.github.io pull request #33
Opened 2018-08-30 19:19 UTC by wmangelardo

Caros,

Estou enviando a atualização da documentação contendo as 2 novas variáveis que o chat embedded envia para o bot. Uma é a **contextData** contendo informações do contexto de onde o bot está integrado (url da página, hostname, query parameters da página etc, útil para conseguir extrair adwords, origem, campanha da url e assim identificar onde quais campanhas de marketing estão gerando mais retorno. A outra variavéis é a **extraData** que pode conter qualquer informação que pode ser util para aquele bot.

2018-08-30 21:04 UTC, rafael-org approved these changes

2018-08-31 21:58 UTC, Aleslem requested changes
A instrução sobre os novos parâmetros estão OK.

No entanto, somente agora percebi que fazemos na documentação, várias referências a "Bot".

O ideal seria substituirmos todas as referência de "Bot" para "Chatbot".

2018-08-31 22:58 UTC, wmangelardo commented
Atualizei a palavra Bot para Chatbot

2018-08-31 23:24 UTC, wmangelardo commented
@Aleslem na documentação sobre chat embedded, eu atualizei tudo para Chatbot em itálico e com C maiusculo, porém nas outras páginas muitas vezes aparece chatbot com c minusculo e sem estar em itálico. Você tem alguma preferência sobre um desses dois tipos?

- _Chatbot_
- chatbot

2018-09-03 13:30 UTC, Aleslem approved these changes

2018-09-03 13:31 UTC, Aleslem commented
Acho que ficou bom assim.
Se necessário, padronizamos depois.

2018-09-03 13:32 UTC, merged

2018-09-03 14:40 UTC, Aleslem commented
Encontrei o erro que comentei..  faltou o "r" na palavra determinar.  

"Id Web Chat
O Id Web Chat é o identificador da “identidade” do Chatbot, a qual é usada pra ""determina"" inúmeras informações...."

Outra sugestão seria substituir as preposições "pra" por "para".
Por se tratar de uma documentação, achei o "pra" muito informal.